version: '3.8'

services:
  database:
    image: mongo:6.0

  web-app:
    build: .
    ports:
      - "8085:3000"
    environment:
      - DATABASE_URL=mongodb://database:27017/sre_db
    depends_on:
      - database