apiVersion: apps/v1
kind: Deployment
metadata:
  name: mi-app-sre-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mi-app-sre
  template:
    metadata:
      labels:
        app: mi-app-sre
    spec:
      containers:
      - name: web-app
        image: mi-app-sre:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
          name: web #Agrego esta línea para bautizar el puerto
        env:
        - name: DATABASE_URL
          value: "mongodb://mongodb-service:27017/sre_db" # <-- Mantenemos el puerto falso
        
        # 🛡️ ¡SRE CLAVE! Sondas de Monitoreo Interno
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: mi-app-sre-service
spec:
  type: ClusterIP
  selector:
    app: mi-app-sre
  ports:
    - port: 3000
      targetPort: 3000